format:
  input: "MsFormatMassbank"
  output: "MsFormatMsp"
mapping:
  input: "mapping/massbank.yaml"
  output: "mapping/nist-msp.yaml"
data:
  input: "input/recdata"
  output: "output"
filename_out_schema: "spectra.msp"
spectra_per_block: 500