format:
  input: MsFormatMgf
  output: MsFormatMassbank
mapping:
  input: ./mapping/gnps_cleaned.yml
  output: ./mapping/massbank.yaml
data:
  input: ./input/gnps_short
  output: ./output
  cache: ./cache
processing:
- task: fix_data
  params:
    source: input/instrument_type.csv
- task: compute_from_smiles
  params:
    properties:
    - exactmass
    - formula
    - inchi
    - inchikey
- task: add_date
  params:
    date: 2024.01.24
- task: add_variable
  params:
    variable: license
    value: CC BY
- task: filter_relint
  params:
    relint: 0.003
- task: remove_special_characters
  params: []
- task: remove_duplicate_peaks
  params:
    delta: 0.0001
- task: compute_splash
  params: []
spectra_per_file: 1000
files_per_block: 1
filename_out_schema: '{ACCESSION}.txt'

